### ISSUE TITLE
Ticket creation fails when no SMTP daemon is running

### ISSUE THREAD

**Issue by mongrelion** [leesmith/ticket_mule#12]
Application overall is totally great, but when trying to create a new ticket and there is no SMTP dameon running, it just crashes. Definitely there should be an option at the admin dashboard that notifies me if no daemon is running, so I won't be able to send email notifications and validate that case in order to avoid the crashing when creating a new ticket.

**Comment by leesmith** [comment]
Did you misconfigure ActionMailer?

**Comment by mongrelion** [comment]
I've done nothing but what the README.rdoc file says. Note that I have not installed a mailer software like postfix nor sendmail on my system, so maybe that's why the application is crashing.
