### ISSUE TITLE
SQLite3::SQLException: no such column: "updated_at DESC"

### ISSUE THREAD

**Issue by craigsaboe** [leesmith/ticket_mule#7]
"ActiveRecord::StatementInvalid in Dashboard#index" error shown immediately on login with a fresh install. The error can be traced to Line 24 of dashboard#index, which uses a named_scope called "@active_tickets" that is defined in models/ticket.rb, Line 24. Specifically, the error points to the order clause (... :order => ['updated_at DESC']). I believe (RoR newbie here) that the square brackets cause that to be interpreted as a literal column name rather than a clause to be parsed by ActiveRecord, because removing them so it reads (... :order => 'updated_at DESC') allows TM to run successfully for me.

Running Rails 2.3.8 and Ruby 1.9.1 on Ubuntu 10.04. I'm assuming its been working for all of you guys, so I don't know if its a regression somewhere or if I'm using a nonstandard version of something. Like I said, newbie here, so I'm putting all this in the issue tracker here for appogee to see. If you want me to submit a patch or something, I can, I just need to figure out how to for GitHub and all. Let me know if you need more info from me.

**Comment by ghost** [comment]
The only difference for me is ruby...I've never run TM on ruby 1.9.  Regardless, I've removed the array notation on those order clauses for those 3 named scopes.
